on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
  push:
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        lambdapi-version: [master]
    runs-on: ubuntu-latest
    steps:
      - name: Check out lib
        uses: actions/checkout@v2
      - name: Install ocaml and opam
        uses: ocaml/setup-ocaml@v2
      - name: Install lambdapi dependencies
        run: opam install dune bindlib timed sedlex menhir pratter yojson cmdliner why3
      - name: Check out lambdapi ${{ matrix.lambdapi-version }}
        run: git clone --depth 1 --branch ${{ matrix.lambdapi-version }} https://github.com/Deducteam/lambdapi.git
      - name: Install lambdapi
        run: |
          cd lambdapi
          eval $(opam env)
          make install
      - name: Check lib
        run: |
          eval $(opam env)
          make
