on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lambdapi-version: [master]
    steps:
      - name: install ocaml and opam
        uses: ocaml/setup-ocaml@v2
      - name: install lambdapi dependencies
        run: opam install dune bindlib timed sedlex menhir pratter yojson cmdliner why3
      - name: install lambdapi
        run: |
          git clone https://github.com/Deducteam/lambdapi
          cd lambdapi
          eval $(opam env)
          make install
          which lambdapi
      - name: check out lib
        uses: actions/checkout@v2
      - name: compile lib
        run: |
          eval $(opam env)
          make
