on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        lambdapi-version: [lambdapi,lambdapi.2.6.0] #,lambdapi.2.5.1,lambdapi.2.5.0,lambdapi.2.4.1,lambdapi.2.4.0,lambdapi.2.3.1]
    runs-on: ubuntu-latest
    steps:
      - name: Check out library
        uses: actions/checkout@v4
      - name: Install ocaml and opam
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.2.1
          # lambdapi.2.3.0 dependencies require ocaml < 5.0.0
      - name: Install required libraries
        run: sudo apt-get install -y libev-dev
      - name: Setup opam (when testing the development version of lambdapi)
        run: opam pin -n --dev-repo lambdapi
        if: matrix.lambdapi-version == 'lambdapi'
      - name: Install ${{ matrix.lambdapi-version }}
        run: opam install ${{ matrix.lambdapi-version }}
      - name: Check library
        run: |
          eval $(opam env)
          make
