on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#      - name: Working directory
#        run: pwd
      - name: Check out lib
        uses: actions/checkout@v2
      - name: Install ocaml and opam
        uses: ocaml/setup-ocaml@v2
      - name: Install lambdapi dependencies
        run: opam install dune bindlib timed sedlex menhir pratter yojson cmdliner why3
      - name: Check out lambdapi
        uses: actions/checkout@v2
        with:
          repository: https://github.com/Deducteam/lambdapi
      - name: Install lambdapi
        run: |
          cd lambdapi
          eval $(opam env)
          make install
      - name: Check lib
        run: |
          eval $(opam env)
          make
